FROM python:3.11-slim

WORKDIR /app

COPY producers/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set PYTHONPATH to include the current directory for module discovery
ENV PYTHONPATH=/app

ENTRYPOINT ["python", "producers/iot_sensor_producer.py"]
